### ISSUE TITLE
Install Redis Stack on Ubuntu 22.04

### ISSUE THREAD

**Issue by songweionline** [redis-stack/redis-stack-docs#85] opened 2022-10-03 02:46 UTC
how to install redis-stack-server on ubuntu22.-4

**Comment by chayim** [comment] 2022-10-09 08:42
redis-stack is currently unsupported on ubuntu 22.04. This is in the backlog!

**Comment by chayim** [comment] 2022-10-09 08:51
Closing - duplicate of #69

**Closed by chayim** 2022-10-09 08:51 UTC
